
author: Ali Akhtarzada
module: Swooft
readme: README.md
hide_documentation_coverage: true

theme: docs/jazzy-theme/
abstract: docs/abstracts/*.md

author_url: https://github.com/aliak00/
github_url: https://github.com/aliak00/swooft/
root_url: https://github.com/aliak00/swooft/

xcodebuild_arguments: [
  -workspace,
  Example/Swooft.xcworkspace,
  -scheme,
  Swooft-Example,
  -sdk,
  iphonesimulator10.3
]

custom_categories:
  - name: AsyncTask
    children:
      - AsyncTask
  - name: Atomics
    children:
      - AtomicInt
  - name: Collections
    children:
      - RingBuffer
  - name: Logger
    children:
      - Logger
  - name: Result
    children:
      - Result
  - name: Tasker
    children:
      - AnyTask
      - InterceptCommand
      - Task
      - TaskError
      - TaskHandle
      - TaskInterceptor
      - TaskInterceptorConfiguration
      - TaskManager
      - TaskState
  - name: Utils
    children:
      - Weak
