theme: apple
min_acl: public
skip_undocumented: true
hide_documentation_coverage: true
exclude:
  - Tests/**
github_url: https://www.github.com/aliak00/Tasker
copyright: © 2018-2019 Ali Akhtarzada
xcodebuild_arguments: ["-scheme", "Tasker-macOS", "-project", "Xcode/Tasker.xcodeproj", "-derivedDataPath", ".build/DerivedData"]
abstract: docs/abstracts/*.md

custom_categories:
  - name: Task Management
    children:
      - Task
      - Handle
      - TaskManager
      - Interceptor
      - TaskReactor
      - TaskReactorConfiguration
      - TaskError
      - TaskState
      - InterceptCommand
      - Result
  - name: Logging
    children:
     - Logger
     - LogTags
     - LogLevel
  - name: "Async Await"
    children:
      - async(_:completion:)
      - await(timeout:block:)
      - task(_:)
      - AnyTask
      - AnyResult
  - name: URL Session Interceptor
    children:
      - URLTaskManager
      - URLTask
      - URLTaskInterceptor
      - URLTaskReactor
      - URLTaskManagerError
