
author: Ali Akhtarzada
module: Swooft
readme: README.md
hide_documentation_coverage: true

theme: docs/jazzy-theme/
abstract: docs/abstracts/*.md

author_url: https://github.com/aliak00/
github_url: https://github.com/aliak00/swooft/
root_url: https://github.com/aliak00/swooft/

xcodebuild_arguments: [
  -workspace,
  Example/Swooft.xcworkspace,
  -scheme,
  Swooft-Example,
  -sdk,
  iphonesimulator11.1,
  -derivedDataPath,
  build/DerivedData
]

custom_categories:
  - name: Atomics
    children:
      - AtomicInt
  - name: Collections
    children:
      - Cache
      - LinkedList
      - LinkedListNode
      - RingBuffer
  - name: Logger
    children:
      - Logger
  - name: Profiler
    children:
      - Profiler
      - ProfilerConfiguration
      - ProfilerResults
  - name: Result
    children:
      - AnyResult
      - Result
  - name: Tasker
    children:
      - AnyTask
      - InterceptCommand
      - Task
      - TaskError
      - TaskHandle
      - TaskInterceptor
      - TaskReactor
      - TaskReactorConfiguration
      - TaskManager
      - TaskState
  - name: Utils
    children:
      - Weak
