theme: apple
min_acl: public
skip_undocumented: true
hide_documentation_coverage: true
exclude:
  - Tests/**
github_url: https://www.github.com/aliak00/Tasker
copyright: © 2018-2019 Ali Akhtarzada
xcodebuild_arguments: ["-scheme", "Tasker-macOS", "-project", "Xcode/Tasker.xcodeproj", "-derivedDataPath", ".build/DerivedData"]
abstract: docs/abstracts/*.md

custom_categories:
  - name: Task Management
    children:
      - Task
      - TaskError
      - TaskState
      - Handle
      - TaskManager
      - Interceptor
      - InterceptCommand
      - Reactor
      - ReactorConfiguration
      - Result
  - name: Logging
    children:
     - Logger
     - LogTags
     - LogLevel
  - name: AnyTask
    children:
      - AnyTask
      - AnyResult
      - task(closingOver:)
      - task(executing:)
  - name: Async Await
    children:
      - async(_:completion:)
      - await(timeout:block:)
  - name: URL Session Interceptor
    children:
      - URLTaskManager
      - URLTask
      - URLTaskInterceptor
      - URLTaskReactor
      - URLTaskManagerError
