os: osx
osx_image: xcode10.2
language: swift
cache:
  bundler: true
  directories:
    - build

bundler_args: --without documentation --without development --deployment --jobs=3 --retry=3

matrix:
  include:
    # - name: "iOS"
    #   script:
    #     - scripts/test-ios.sh
    - name: "MacOS"
      script:
        - swift test
    # - name: "Pod lint"
    #   script:
    #     - bundle exec pod lib lint
    # - name: "Build carthage"
    #   script:
    #     - scripts/carthage-build.sh
    # - name: "Docs"
    #   script:
    #     - bundle exec jazzy
    #   deploy:
    #     local_dir: docs
    #     provider: pages
    #     skip_cleanup: true
    #     github_token: $GITHUB_TOKEN
    #     on:
    #       branch: main
    #       tags: true