os: osx
osx_image: xcode11.5
language: swift
cache:
  bundler: true
  directories:
    - build

bundler_args: --without documentation --without development --deployment --jobs=3 --retry=3

matrix:
  include:
    - name: "iOS"
      script:
        - scripts/test-ios.sh
    - name: "MacOS codecov"
      script:
        - swift package generate-xcodeproj
        - xcodebuild -scheme Tasker-Package -enableCodeCoverage YES test | xcpretty
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - name: "MacOS"
      script:
        - swift test
    - name: "Pod lint"
      script:
        - bundle exec pod lib lint
    - name: "Build carthage"
      script:
        - scripts/carthage-build.sh
    - name: "Docs"
      script:
        - bundle exec jazzy
      deploy:
        local_dir: docs
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        on:
          branch: main
          tags: true